# Generated by Django 6.0.4 on 2026-04-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mobile_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
