# Generated by Django 6.0.4 on 2026-04-15

from django.db import migrations
from django.db import models


def set_blank_mobile_numbers_to_null(apps, schema_editor):
    """
    Convert empty-string mobile numbers to NULL.
    """
    user_model = apps.get_model('core', 'User')
    user_model.objects.filter(mobile_number='').update(mobile_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            set_blank_mobile_numbers_to_null,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

